In [4]:
import numpy as np
from tensorflow.keras.layers import Embedding

e = Embedding(200, 32, input_length=50)
# define documents
docs = [
    "Well done!",
    "Good work",
    "Great effort",
    "nice work",
    "Excellent!",
    "Weak",
    "Poor effort!",
    "not good",
    "poor work",
    "Could have done better.",
]
# define class labels
labels = np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [5]:
from tensorflow.keras.preprocessing.text import one_hot

# integer encode the documents
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[1, 36], [29, 10], [28, 41], [13, 10], [25], [37], [31, 41], [18, 29], [31, 10], [19, 11, 36, 47]]


In [6]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding="post")
print(padded_docs)

[[ 1 36  0  0]
 [29 10  0  0]
 [28 41  0  0]
 [13 10  0  0]
 [25  0  0  0]
 [37  0  0  0]
 [31 41  0  0]
 [18 29  0  0]
 [31 10  0  0]
 [19 11 36 47]]


In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense

# define the model
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation="sigmoid"))
# compile the model
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
# summarize the model
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 4, 8)              400       
                                                                 
 flatten (Flatten)           (None, 32)                0         
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None


In [8]:
# fit the model
model.fit(padded_docs, labels, epochs=50, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print("Accuracy: %f" % (accuracy * 100))

Accuracy: 89.999998


In [9]:
from numpy import array
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense
from tensorflow.keras.layers import Embedding

# define documents
docs = [
    "Well done!",
    "Good work",
    "Great effort",
    "nice work",
    "Excellent!",
    "Weak",
    "Poor effort!",
    "not good",
    "poor work",
    "Could have done better.",
]
# define class labels
labels = array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])
# integer encode the documents
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)
# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding="post")
print(padded_docs)
# define the model
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation="sigmoid"))
# compile the model
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
# summarize the model
print(model.summary())
# fit the model
model.fit(padded_docs, labels, epochs=50, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print("Accuracy: %f" % (accuracy * 100))

[[1, 36], [29, 10], [28, 41], [13, 10], [25], [37], [31, 41], [18, 29], [31, 10], [19, 11, 36, 47]]
[[ 1 36  0  0]
 [29 10  0  0]
 [28 41  0  0]
 [13 10  0  0]
 [25  0  0  0]
 [37  0  0  0]
 [31 41  0  0]
 [18 29  0  0]
 [31 10  0  0]
 [19 11 36 47]]
Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 4, 8)              400       
                                                                 
 flatten_1 (Flatten)         (None, 32)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None
Accuracy: 89.999998
