In [ ]:
import sys
!{sys.executable} -m pip install numpy

In [2]:
import numpy as np

In [3]:
a1 = np.arange(10)
print(a1)
print(a1.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [4]:
a2 = np.arange(0,10,2)
print(a2)

[0 2 4 6 8]


In [8]:
a3 = np.zeros(5)
print(a3)
print(a3.shape)

[0. 0. 0. 0. 0.]
(5,)


In [11]:
a4 = np.zeros((2,3))
print(a4.shape)
print(a4)

(2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
a5 = np.full((2,3),8)
print(a5)

[[8 8 8]
 [8 8 8]]


In [15]:
a6 = np.eye(4)
print(a6)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
a7 = np.random.random((2,4))
print(a7)

[[0.53749999 0.24864656 0.06886703 0.04011139]
 [0.61170418 0.93314195 0.30992874 0.99164352]]


In [19]:
list1 = [1,2,3,4,5]

r1 = np.array(list1)
print(r1)

[1 2 3 4 5]


In [23]:
names = np.array(['Ann', 'Joe', 'Mark'])

heights = np.array([1.5, 1.78, 1.6])
weights = np.array([65, 46, 59])

In [24]:
bmi = weights/heights **2

print(bmi)

[28.88888889 14.51836889 23.046875  ]
